"""add new table

Revision ID: 017b109cfdb2
Revises: 9886457cce4f
Create Date: 2026-09-15 19:03:28.681063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017b109cfdb2'
down_revision: Union[str, Sequence[str], None] = '9886457cce4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('users_tier_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'tier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_tier_id_fkey'), 'users', 'subscription_tiers', ['tier_id'], ['id'])
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
