"""update schema

Revision ID: 1fce8e1106e3
Revises: 77ed505b5679
Create Date: 2026-09-17 20:35:49.125505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fce8e1106e3'
down_revision: Union[str, Sequence[str], None] = '77ed505b5679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('max_token_schema', sa.Text(), nullable=False))
    op.drop_column('models', 'context_window_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('context_window_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('models', 'max_token_schema')
    # ### end Alembic commands ###
