"""updated user schema

Revision ID: 4c4dbf1b2d0d
Revises: 83dce0213591
Create Date: 2026-09-14 21:45:01.785184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4dbf1b2d0d'
down_revision: Union[str, Sequence[str], None] = '83dce0213591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tier_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tier_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
