"""update Models schema

Revision ID: 4fa87aa83f05
Revises: 1368597b7ad2
Create Date: 2026-09-17 01:15:25.008888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa87aa83f05'
down_revision: Union[str, Sequence[str], None] = '1368597b7ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('context_window_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'context_window_limit')
    # ### end Alembic commands ###
