"""Update Schema

Revision ID: 65d2ed0c2a31
Revises: 017b109cfdb2
Create Date: 2026-09-16 21:29:15.084414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d2ed0c2a31'
down_revision: Union[str, Sequence[str], None] = '017b109cfdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
