"""update schema

Revision ID: 66eb9b3cb5c4
Revises: 3e712b55b30f
Create Date: 2026-09-19 07:11:56.649080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eb9b3cb5c4'
down_revision: Union[str, Sequence[str], None] = '3e712b55b30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('context_budget_tokens', sa.Integer(), server_default='100000', nullable=False))
    op.drop_column('models', 'history_budget_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('history_budget_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('models', 'context_budget_tokens')
    # ### end Alembic commands ###
