"""rename price columns to per-1m

Revision ID: 69dcc1a05786
Revises: 3d6b838a3069
Create Date: 2026-09-14 18:50:57.700588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69dcc1a05786'
down_revision: Union[str, Sequence[str], None] = '3d6b838a3069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('input_price_per_1M', sa.Numeric(precision=12, scale=6), nullable=False))
    op.add_column('models', sa.Column('output_price_per_1M', sa.Numeric(precision=12, scale=6), nullable=False))
    op.drop_column('models', 'input_price_per_1k')
    op.drop_column('models', 'output_price_per_1k')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('output_price_per_1k', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=False))
    op.add_column('models', sa.Column('input_price_per_1k', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=False))
    op.drop_column('models', 'output_price_per_1M')
    op.drop_column('models', 'input_price_per_1M')
    # ### end Alembic commands ###
