"""update schema

Revision ID: 97a17ddb53d9
Revises: 1daff9ed5bbe
Create Date: 2026-09-18 01:28:40.837730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a17ddb53d9'
down_revision: Union[str, Sequence[str], None] = '1daff9ed5bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('daily_context_quota', sa.BigInteger(), server_default='100000', nullable=False))
    op.add_column('models', sa.Column('history_budget_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('models', sa.Column('supports_temperature', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('usage_records', sa.Column('context_tokens', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_records', 'context_tokens')
    op.drop_column('models', 'supports_temperature')
    op.drop_column('models', 'history_budget_tokens')
    op.drop_column('api_keys', 'daily_context_quota')
    # ### end Alembic commands ###
