"""update message schema

Revision ID: a845050facdc
Revises: ffd9bf3a39cc
Create Date: 2026-09-22 22:17:31.016184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a845050facdc'
down_revision: Union[str, Sequence[str], None] = 'ffd9bf3a39cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model', sa.String(), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'model')
    # ### end Alembic commands ###
