"""update schema

Revision ID: df27baa197c0
Revises: 97a17ddb53d9
Create Date: 2026-09-19 06:54:25.375043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df27baa197c0'
down_revision: Union[str, Sequence[str], None] = '97a17ddb53d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('requires_temperature', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('models', 'supports_temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('supports_temperature', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('models', 'requires_temperature')
    # ### end Alembic commands ###
