"""update UsageRecords Schema

Revision ID: ffd9bf3a39cc
Revises: 66eb9b3cb5c4
Create Date: 2026-09-22 20:04:36.627620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd9bf3a39cc'
down_revision: Union[str, Sequence[str], None] = '66eb9b3cb5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_records', 'latency_ms')
    op.drop_column('usage_records', 'cost_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('cost_usd', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True))
    op.add_column('usage_records', sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
